config:
  target: https://java-func-niantoni.azurewebsites.net
  processor: "./funcs.js"
  payload:
    path: "data.csv"
    fields:
      - "city"
      - "street"
  phases:
    - duration: 20
      arrivalRate: 1
      name: "Warm up application"
    - duration: 180
      arrivalRate: 3
      name: "Stream user activities"
  defaults:
    headers:
      x-functions-key: "oqJIz74tMmzxaVrgZzVZoLRJmnXsYsALOoCc7t73ET580YoUdBif8A=="
scenarios:
  - flow:
      - log: "User Activity stream running"
      - function: "createPayloadVars"
      - post:
          url: "/api/activities"
          json:
            UserId: "randomusername"
            Timestamp: "{{ timestamp }}"
            SessionId: "{{ eventId }}"
            Event: "{{ event }}"
            EventPayload: "{{ eventPayload }}"
            Source: "{{ source }}"
            Page: "RandomFrontendPage"
          capture:
            json: "$.eventId"
            as: "eventId"