config:
  target: https://[REPLACE:FUNCTION-APP].azurewebsites.net
  processor: "./funcs.js"
  payload:
    path: "data.csv"
    fields:
      - "city"
      - "street"
  phases:
    - duration: 20
      arrivalRate: 1
      name: "Warm up application"
    - duration: 180
      arrivalRate: 3
      name: "Stream user activities"
  defaults:
    headers:
      x-functions-key: "[REPLACE:FUNCTION_KEY]"
scenarios:
  - flow:
      - log: "User Activity stream running"
      - function: "createPayloadVars"
      - post:
          url: "/api/activities"
          json:
            userId: "{{ userId }}"
            timestamp: "{{ timestamp }}"
            sessionId: "{{ eventId }}"
            event: "{{ event }}"
            eventPayload: "{{ eventPayload }}"
            source: "{{ source }}"
            page: "RandomFrontendPage"
          capture:
            json: "$.eventId"
            as: "eventId"